import configparser

config = configparser.ConfigParser()
config.read("/home/mdo/portal_mdo_reborn/portal_mdo_api/config.ini")

DEFAULT_DB_HOST = config["DEFAULT_DATABASE"]["HOST"]
DEFAULT_DB_PORT = int(config["DEFAULT_DATABASE"]["PORT"])
DEFAULT_DB_USERNAME = config["DEFAULT_DATABASE"]["USERNAME"]
DEFAULT_DB_KUNCI_GEMBOK = config["DEFAULT_DATABASE"]["KUNCI_GEMBOK"]
DEFAULT_DB_DATABASE = config["DEFAULT_DATABASE"]["DATABASE"]
DEFAULT_DB_WRITE_TIMEOUT = int(config["DEFAULT_DATABASE"]["WRITE_TIMEOUT"])
DEFAULT_DB_READ_TIMEOUT = int(config["DEFAULT_DATABASE"]["READ_TIMEOUT"])
DEFAULT_DB_CONNECT_TIMEOUT = int(config["DEFAULT_DATABASE"]["CONNECT_TIMEOUT"])
DEFAULT_DB_MAX_ALLOWED_PACKET = int(config["DEFAULT_DATABASE"]["MAX_ALLOWED_PACKET"])

APP_HOST = config["APPLICATION"]["HOST"]
APP_PORT = config["APPLICATION"]["PORT"]
APP_JWT_SECRET_KEY = config["APPLICATION"]["JWT_SECRET_KEY"]
APP_ACCESS_TOKEN_EXPIRES = config["APPLICATION"]["ACCESS_TOKEN_EXPIRES"]
APP_REFRESH_TOKEN_EXPIRES = config["APPLICATION"]["REFRESH_TOKEN_EXPIRES"]
APP_HTTP_PROXY = config["APPLICATION"]["HTTP_PROXY"]
APP_HTTPS_PROXY = config["APPLICATION"]["HTTPS_PROXY"]
APP_API_LOG_PATH = config["APPLICATION"]["API_LOG_PATH"]